cookie:
  secret: 'REPLACE SECRET IN LOCAL.YAML'
mysql:
  host: 'localhost'
  user: 'assure'
  password: 'assure_test'
  database: 'assurenote'
translator:
  CLIENT_ID: ''
  CLIENT_SECRET: ''
debug_user:
  loginName: 'tsunade'
assurenote:
    basepath: ''
passport:
    resolveURL: 'localhost:3000'
    FACEBOOK_APP_ID: ''
    FACEBOOK_APP_SECRET: ''
    TWITTER_CONSUMER_KEY: ''
    TWITTER_CONSUMER_SECRET: ''
    GITHUB_CLIENT_ID: ''
    GITHUB_CLIENT_SECRET: ''
