cookie:
  secret: 'REPLACE SECRET IN LOCAL.YAML'
mysql:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'ads'
translator:
  CLIENT_ID: ''
  CLIENT_SECRET: ''
debug_user:
  loginName: 'tsunade'
ads:
    basePath: ""
passport:
    resolveURL: 'localhost:3000'
    FACEBOOK_APP_ID: ''
    FACEBOOK_APP_SECRET: ''
    TWITTER_CONSUMER_KEY: ''
    TWITTER_CONSUMER_SECRET: ''
    GITHUB_CLIENT_ID: ''
    GITHUB_CLIENT_SECRET: ''
