cookie:
  secret: 'REPLACE SECRET IN LOCAL.YAML'
mysql:
  host: 'localhost'
  user: 'assure'
  password: 'assure_test'
  database: 'assurenote'
rec:
  URL: 'http://localhost:3001/api/3.0/'
sync:
  URL: 'http://localhost:3002'
translator:
  CLIENT_ID: ''
  CLIENT_SECRET: ''
debug_user:
  loginName: 'tsunade'
assurenote:
    basepath: ''
analytics:
    Analytics_UA: '' #e.g., UA-********-*
    Analytics_Domain: '' #e.g., www.example.com
passport:
    resolveURL: 'localhost:3000'
    FACEBOOK_APP_ID: ''
    FACEBOOK_APP_SECRET: ''
    TWITTER_CONSUMER_KEY: ''
    TWITTER_CONSUMER_SECRET: ''
    GITHUB_CLIENT_ID: ''
    GITHUB_CLIENT_SECRET: ''
