#!/bin/sh

SourceDir=./src/org/assurenote/
build=src/TypeScript/

# These order of files is VERY IMPORTANT. 
# DO NOT CHANGE THE ORDER WITHOUT NECESSITY.
source=
source="${source} AssureNoteParser"
target="AssureNoteParser"
#
libs=""
libs="${libs} ${build}LibAssureNoteParser.ts"
libs="${libs} ${build}/lib/md5.js"

ts=""
for s in ${source}; do
    perl src/TypeScript/ToTypeScript.pl ${SourceDir}${s}.java > "${build}_${s}.ts"
    ts="${ts} ${build}_${s}.ts"
done

cat ${ts} ${libs} > ${build}${target}.ts
rm ${ts}

if [ $# -ne 0 ]; then
    perl src/TypeScript/PackInputFiles.pl $@ >> ${build}${target}.ts
fi


tsc ${build}${target}.ts
