#!/bin/sh

SourceDir=./src/org/assurenote/
build=src/TypeScript/

# These order of files is VERY IMPORTANT. 
# DO NOT CHANGE THE ORDER WITHOUT NECESSITY.
source=
source="${source} AssureNoteParser"
target="AssureNoteParser"
clientdir="../AssureNote/src"
serverdir="../ServerChat/"
#
libs=""
libs="${libs} ${build}LibAssureNoteParser.ts"
libs="${libs} ${build}/lib/md5.js"

ts=""
for s in ${source}; do
    perl src/TypeScript/ToTypeScript.pl ${SourceDir}${s}.java > "${build}_${s}.ts"
    ts="${ts} ${build}_${s}.ts"
done

# First path: Clientside

echo "module AssureNote {" > ${build}${target}.ts
cat ${ts} ${libs} >> ${build}${target}.ts

if [ $# -ne 0 ]; then
    perl src/TypeScript/PackInputFiles.pl $@ >> ${build}${target}.ts
fi
echo "}" >> ${build}${target}.ts

tsc ${build}${target}.ts --module commonjs
cp ${build}${target}.ts ${clientdir}
cp ${build}${target}.js ${clientdir}

# Second path: Serverside

cat ${ts} ${libs} > ${build}${target}.ts

if [ $# -ne 0 ]; then
    perl src/TypeScript/PackInputFiles.pl $@ >> ${build}${target}.ts
fi

tsc ${build}${target}.ts --module commonjs
cp ${build}${target}.ts ${serverdir}
cp ${build}${target}.js ${serverdir}

# Destructor
rm ${ts}
